"""empty message

Revision ID: d62be1b2690b
Revises: c94d7c466ace
Create Date: 2016-10-17 11:38:00.484253

"""

# revision identifiers, used by Alembic.
revision = 'd62be1b2690b'
down_revision = 'c94d7c466ace'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'post',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('post', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('post', 'post',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###
